### ISSUE TITLE
Build OS fails 8 seconds into the build

### ISSUE THREAD

**Issue by ajstrongdev** [rollingrhinoremix/RRR-builder#33]
```sh
Run sudo apt-get install xorriso coreutils squashfs-tools git axel sed -y
Reading package lists...
Building dependency tree...
Reading state information...
coreutils is already the newest version (8.30-3ubuntu2).
sed is already the newest version (4.7-1).
sed set to manually installed.
xorriso is already the newest version (1.5.2-1).
squashfs-tools is already the newest version (1:4.4-1ubuntu0.3).
squashfs-tools set to manually installed.
git is already the newest version (1:2.37.1-0ppa1~ubuntu20.04.1).
The following NEW packages will be installed:
  axel
0 upgraded, 1 newly installed, 0 to remove and 13 not upgraded.
Need to get 58.7 kB of archives.
After this operation, 206 kB of additional disk space will be used.
Get:1 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 axel amd64 2.17.5-1ubuntu1 [58.7 kB]
Fetched 58.7 kB in 0s (1077 kB/s)
Selecting previously unselected package axel.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... [25](https://github.com/rollingrhinoremix/RRR-builder/runs/7544660616?check_suite_focus=true#step:2:26)%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 230284 files and directories currently installed.)
Preparing to unpack .../axel_2.17.5-1ubuntu1_amd64.deb ...
Unpacking axel (2.17.5-1ubuntu1) ...
Setting up axel (2.17.5-1ubuntu1) ...
Processing triggers for man-db (2.9.1-1) ...
http://mirrors.edge.kernel.org/ubuntu/pool/main/c/cd-boot-images-amd64/cd-boot-images-amd64_17_all.deb:
2022-07-[27](https://github.com/rollingrhinoremix/RRR-builder/runs/7544660616?check_suite_focus=true#step:2:28) 16:27:12 ERROR [40](https://github.com/rollingrhinoremix/RRR-builder/runs/7544660616?check_suite_focus=true#step:2:41)4: Not Found.
Error: Process completed with exit code 8.
```
It seems to not be able to find cd-boot-images

**Comment by cat-master21** [comment]
Updated the deb file link it so should be fixed now

**Comment by ajstrongdev** [comment]
cat-master21: Issue persists in the next make release. Same error.

**Comment by cat-master21** [comment]
The issue was with axel being downloaded as verbose. Builds now succeed.
